from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    Image
)
from reportlab.lib.units import inch
from datetime import datetime
import os


def generate_pdf(
    patient_name,
    emergency_type,
    priority,
    location,
    hospital,
    specialist,
    beds,
    icu,
    ambulance,
    maps_link,
    qr_path
):

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/{patient_name}_Emergency_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # -------------------------
    # Hospital Logo
    # -------------------------

    # Hospital logo will be added later.
    
    # -------------------------
    # Title
    # -------------------------

    story.append(
        Paragraph(
            "<b>Emergency Care Allocation Report</b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    current_time = datetime.now().strftime("%d-%m-%Y %I:%M %p")

    # -------------------------
    # Table Data
    # -------------------------

    data = [

        ["Patient Name", patient_name],

        ["Emergency Type", emergency_type],

        ["Priority", priority],

        ["Generated On", current_time],

        ["Location", location],

        ["Assigned Hospital", hospital],

        ["Assigned Specialist", specialist],

        ["Available Beds", str(beds)],

        ["Available ICU Beds", str(icu)],

        ["Available Ambulances", str(ambulance)],

        ["Google Maps", maps_link]

    ]

    table = Table(data, colWidths=[180, 260])

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (0, -1), colors.lightblue),

        ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),

        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # -------------------------
    # QR Code
    # -------------------------

    if os.path.exists(qr_path):

        story.append(
            Paragraph(
                "<b>Scan QR Code for Hospital Location</b>",
                styles["Heading2"]
            )
        )

        story.append(
            Image(
                qr_path,
                width=2 * inch,
                height=2 * inch
            )
        )

    story.append(Spacer(1, 20))

    # -------------------------
    # AI Recommendation
    # -------------------------

    story.append(
        Paragraph(
            "<b>AI Recommendation</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            "This hospital was selected based on available beds, ICU capacity, ambulance availability, and specialist matching.",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<i>Generated by AI Emergency Care Resource Allocator</i>",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename